[package]
name = "wordler-cli"
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "wordler"
path = "src/main.rs"

[dependencies]
itertools = "0.14.0"
thiserror = "2.0.17"
wordler = { path = "../lib", version = "0.1.0" }
